services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: opeth
      POSTGRES_DB: storedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d storedb"]
      interval: 5s
      retries: 5

  backend:
    build: .
    container_name: go_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=NewSecretKey
      - DB_NAME=storedb
      - DBPath=postgres://postgres:opeth@db:5432/storedb?sslmode=disable

volumes:
  postgres_data:
